<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="blog_1.aspx.cs" Inherits="DATN.PetShop.User.site.blog.blogTest" %>

<asp:Content ID="Content1" ContentPlaceHolderID="cph" runat="server">
    <div style ="width:60%; margin:auto">
        <h1 class="title-article-detail">Bé chó bị bệnh đường ruột - đừng quá lo lắng!</h1>
        <div class="article_content" style="overflow: hidden; margin: 10px 0">
        <p style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><em><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Chó bị bệnh đường ruột là tình trạng phổ biến ở rất nhiều cún cưng được nuôi hiện nay. Theo một nghiên cứu khoa học cho thấy, hơn 60% số cho mắc bệnh đều có những vấn đề liên quan đến đường tiêu hóa.</span></em></p>
        <p style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><em><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Bệnh đường ruột là một trong những chứng bệnh vô cùng nguy hiểm với sức khoẻ của chó và có nguy cơ gây tử vong vô cùng cao. Vì vậy, việc tìm hiểu những dấu hiệu và cách chữa bệnh đường ruột cho cún cưng của chúng ta là một việc vô cùng cần thiết. Cùng PetCity tìm hiểu qua bài viết dưới đây nhé!</span></em></p>
        <p style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">1. Nguyên nhân khiến chó bị bệnh đường ruột</span></strong></p>
        <p style="line-height: 1.8; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">
            <img src="https://www.petcity.vn/media/news/2705_pasted-image-0-78.png" alt="" width="546" height="296"></span></p>
        <p style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Các nguyên nhân dẫn đến việc rối loạn tiêu hóa hay các bệnh đường ruột thường sẽ đến từ thức ăn mà các bé nạp vào cơ thể.</span></p>
        <p style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Những loại thức ăn có thể gây khó chịu cho hệ tiêu hóa và khiến cho chó bị bệnh đường ruột thường thấy là thức ăn không dành cho chó (những bữa ăn hằng ngày của chúng ta), thực phẩm ôi thiu, rác hoặc là các vật phẩm lạ.</span></p>
        <p style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Các loại virus, vi khuẩn gây bệnh đường ruột ở chó phổ biến</span></strong></p>
        <p style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><strong><em><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Parvovirus:</span></em></strong><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> Đây là một loại virus có khả năng gây tử vong cao cho các loài chó, đặc biệt là Rottweilers, American Pit Bull Terrier, Doberman Pinschers, English Springer Spaniels và German Shepherds với khả năng mắc bệnh cao hơn.</span></p>
        <p style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Virus này thường được lây truyền trực tiếp khi các bạn chó mà chúng ta nuôi tiếp xúc với những chú chó khác bị nhiễm bệnh hoặc phân chứa mầm bệnh.</span></p>
        <p style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Việc lây truyền gián tiếp qua các vật thể bị nhiễm phân là hoàn toàn có thể xảy ra vì loại virus này có khả năng sống trong phân đến 3 tuần sau khi vật nuôi bị nhiễm bệnh.</span></p>
        <p style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Loại virus này sau khi vào được cơ thể vật nuôi, chúng sẽ bắt đầu lan truyền rộng khắp và thâm nhập qua các mô sản xuất tế bào máu đặc biệt là niêm mạc ruột non. Bệnh sẽ càng nghiêm trọng hơn khi virus này tiếp cận với máu và các mô bị tổn thương.</span></p>
        <p style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><strong><em><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Vi khuẩn:</span></em></strong><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> Các vi khuẩn làm cho chó bị bệnh đường ruột phổ biến là Salmonella hay E.coli. Trong đó Salmonella và E.coli là 2 loại vi khuẩn gây ra hậu quả nghiêm trọng nhất lên đường ruột của chó, đặc biệt là chó con khi hệ miễn dịch và hệ tiêu hóa còn chưa hoàn thiện.</span></p>
        <p style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Tuy E.coli là một loại khuẩn lành tính, đôi khi còn được xem là lợi khuẩn, nhưng đối với, hệ tiêu hóa của những chú cún con còn yếu hoặc một vài bé không có màng miễn dịch “sữa non” của mẹ sẽ rất dễ bị nhiễm khuẩn, đặc biệt là E.coli, khiến nguy cơ chó bị bệnh đường ruột Parvovirus trở nên nghiêm trọng hơn.</span></p>
        <p style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Nhiều loài vi khuẩn Salmonella có thể gây bệnh đường tiêu hóa. Nhiễm khuẩn Salmonella có thể gây ngộ độc máu nghiêm trọng (nhiễm trùng máu) hoặc viêm ruột.</span></p>
        <p style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Vi khuẩn này thường sẽ liên quan đến nhiễm trùng và các loại bệnh khác ở chó trưởng thành và chó con. Hơn thế nữa, khả năng xảy ra sảy thai ở chó mang thai sẽ cao hơn gấp nhiều lần.</span></p>
        <p style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Do đó, việc lựa chọn phương pháp điều trị sớm và phù hợp theo hướng dẫn của bác sĩ là rất cần thiết để ngăn ngừa ngộ độc máu và các tác động mạnh mẽ hơn của vi khuẩn, đặc biệt là khuẩn đường ruột có khả năng kháng kháng sinh, ảnh hưởng tiêu cực đến sức khỏe cũng như hệ tiêu hóa của những chú chó.</span></p>
        <p style="line-height: 1.8; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">
            <img src="https://www.petcity.vn/media/news/2705_tixung4.jpg" alt="" width="490" height="277"></span></p>
        <p style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Các yếu tố ngoại cảnh</span></strong></p>
        <p style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Bên cạnh các tác nhân vi sinh, điều kiện môi trường sống không tốt cũng có thể là nguyên nhân làm cho chó bị bệnh đường ruột. Điều khiến chủ nuôi cần quan tâm chính là môi trường sống, đặc biệt là nguồn thức ăn của chó liệu có chất lượng đảm bảo hay không?</span></p>
        <p style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Thức ăn của chó bị để lâu ngày có thể dẫn đến hư hỏng, ôi thiu và trở thành môi trường phát triển lý tưởng cho một số loại nấm mốc độc hại, các khuẩn, ký sinh trùng gây nên các bệnh về đường tiêu hóa và đường ruột ở vật nuôi.&nbsp;</span></p>
        <p style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Ngoài ra, khi vật nuôi được cho ăn quá nhiều, sẽ dẫn đến sự dư thừa thức ăn trong hệ tiêu hóa của của vật nuôi. Thức ăn khi không được tiêu hóa kịp là một trong những nguyên nhân chính dẫn đến các căn bệnh đường ruột ở người cũng như ở chó.</span></p>
        <p style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Thêm vào đó, khẩu phần ăn có quá nhiều dầu mỡ rất dễ gây khó tiêu ở các loài vật nuôi, đặc biệt là chó.</span></p>
        <p style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Bên cạnh đó, cũng có nhiều loài chó rất nhạy cảm với việc thay đổi thức ăn đột ngột và dẫn đến tiêu chảy cũng như là các vấn đề về tiêu hóa khác.</span></p>
        <p style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Vì thế, để giảm thiểu khả năng khiến cún cưng bị bệnh đường ruột, chủ nuôi cần phải quan tâm chặt chẽ đến chất lượng khẩu phần ăn và lượng dinh dưỡng cần thiết của chúng mỗi ngày.</span></p>
        <p style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">2. Phòng bệnh và cách chữa chó bị bệnh đường ruột</span></strong></p>
        <p style="line-height: 1.8; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">
            <img src="https://www.petcity.vn/media/news/2705_2304_benh-thuong-gap-o-cho-va-canh-chua-tri-phong-benh-hieu-qua-33124.jpg" alt="" width="500" height="374"></span></p>
        <p style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Bệnh đường ruột ảnh hưởng vô cùng nghiêm trọng đến sức khỏe và vòng đời của một chú chó. Vậy khi chó bị bệnh đường ruột thì phải làm sao, cách để phòng bệnh như thế nào?</span></p>
        <p style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Nhìn chung, bệnh đường ruột ở chó nguyên nhân xuất phát từ một số loại khuẩn đường ruột và quan trọng hơn hết vẫn là chế độ ăn và dinh dưỡng hằng ngày của chúng. Vì vậy, để phòng tránh cún cưng bị bệnh đường ruột, chủ nuôi cần phải chú ý đến những điều sau:</span></p>
        <ul style="margin-top: 0; margin-bottom: 0; padding-inline-start: 48px;">
            <li style="list-style-type: disc; font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Tẩy giun sán và tiêm phòng vacxin 7 bệnh định kỳ cho chó (đặc biệt là khi chó được 45 ngày tuổi, cần được tiêm phòng bệnh Parvo và bệnh Care ở chó) để đảm bảo bệnh đường ruột được phòng ngừa triệt để.</span></li>
            <li style="list-style-type: disc; font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Môi trường sống của chó nên được giữ gìn vệ sinh sạch sẽ và giặt giũ định kỳ để ngăn ngừa sự sản sinh các loại vi khuẩn và nấm mốc ở nơi ở của chúng.</span></li>
            <li style="list-style-type: disc; font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Các dụng cụ để chứa thức ăn của chó cũng cần phải được vệ sinh kỹ lưỡng. Theo định kỳ, có thể ngâm các công cụ dụng cụ hằng ngày mà cho tiếp xúc với nước tẩy gia dụng được pha loãng để có thể bất hoạt vi khuẩn, virus và mầm bệnh tiềm ẩn.</span></li>
        </ul>
        <p style="line-height: 1.8; margin-top: 0pt; margin-bottom: 0pt; text-align: center;">
            <img src="https://www.petcity.vn/media/news/2705_cho-bi-benh-duong-ruot-6.jpg" alt="" width="568" height="398"></p>
        <p style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Chó bị bệnh đường ruột nên cho ăn gì?</span></strong></p>
        <p style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Ngoài ra, một số điều về dinh dưỡng người nuôi cần chú ý khi bé cún bị đường ruột bao gồm:</span></p>
        <p style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Thức ăn phải được nấu chín tuyệt đối không cho chúng ăn thực phẩm sống vì thịt sống rất có thể mang theo mầm bệnh, ảnh hưởng đến hệ tiêu hóa và làm cho cún cưng bị bệnh đường ruột cấp tính. Tuy nhiên, các thực phẩm khi được làm chín cần tránh các biện pháp chiên, xào nhiều dầu mỡ gây khó tiêu cho chúng.</span></p>
        <p style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Chủ nuôi không nên cho thú cưng của mình ăn thức ăn quá nóng, quá cay hay quá chua. Những thực phẩm ngọt như kẹo, socola hay kem cũng cần phải hạn chế.</span></p>
        <p style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Nguồn nước của chó cũng cần phải đảm bảo là nguồn nước sạch, không bị nhiễm bẩn. Nước trước khi cho chúng uống cũng cần phải được nấu chín, không được uống nước lã vì rất có thể nguồn nước ấy tạo điều kiện cho các ký sinh trùng, giun sán và vi khuẩn trong nước xâm nhập vào đường ruột của thú nuôi gây bệnh.</span></p>
        <p style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Quan trọng nhất là khi chó bị bệnh đường ruột cần phải được thực hiện chữa trị kịp thời cũng như là có biện pháp dinh dưỡng và cách ly phù hợp để tránh lây lan sang các loài vật nuôi khác trong nhà.</span></p>
        <p style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Chữa bệnh đường ruột cho chó</span></strong></p>
        <p style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">“Phòng bệnh hơn chữa bệnh” là một việc vô cùng quan trọng. Tuy nhiên, nếu chẳng may chó bị bệnh đường ruột thì phải làm sao và khi chó bị bệnh đường ruột thì nên cho ăn gì? Hãy cùng chúng mình tìm hiểu nhé</span></p>
        <p style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Biện pháp điều trị tạm thời được các tổ chức y tế khuyến cáo là khi phát hiện chó có vấn đề về bệnh đường ruột cũng như bệnh tiêu hóa, điều đầu tiên nên làm chính là ngừng cho ăn và cho chúng uống nhiều nước.</span></p>
        <p style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Bên cạnh đó, trong những trường hợp cấp bách không đưa chó đi khám được, kiến thức về cách chữa bệnh cho cún cưng bị bệnh đường ruột cũng nên được chủ nuôi trang bị kỹ lưỡng.</span></p>
        <ul style="margin-top: 0; margin-bottom: 0; padding-inline-start: 48px;">
            <li style="list-style-type: disc; font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Đối với chó bị mất nước nhẹ và không có tiền sử nôn mửa, ta có thể cấp nước bổ sung cho chúng bằng các dung dịch điện giải, đường uống để bù nước, bù khoáng natri và kali bị mất qua đường ruột</span></li>
            <li style="list-style-type: disc; font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Đối với chó đi ngoài và nôn mửa, các biện pháp cấp nước hay cho ăn không được các bác sĩ thú ý khuyên dùng. Các dưỡng chất bị mất đi, cần phải được cung cấp lại qua đường tiêm truyền.</span></li>
        </ul>
        <p style="line-height: 1.7999999999999998; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Trường hợp đã xác định được chính xác cấp độ bệnh đường ruột của chó, cách chăm sóc chó của chúng ta cũng cần phải được điều chỉnh để đạt hiệu quả điều trị tốt nhất:</span></p>
        <ul style="margin-top: 0; margin-bottom: 0; padding-inline-start: 48px;">
            <li style="list-style-type: disc; font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Đối với bệnh viêm đường ruột: Ngoài việc ngừng cho ăn và cấp nước, nếu chó nôn mửa thì chủ có thể tạm thời dùng các loại thuốc như Anticholinergic cùng Clopromazin và một số loại thuốc an thần khác để giúp chó của chúng ta ổn định hơn trước khi đến bác sĩ thú y.</span></li>
            <li style="list-style-type: disc; font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Đối với bệnh rối loạn tiêu hóa, chúng ta nên ngừng cho chó ăn một ngày. Sang ngày thứ 2 thì có thể cho chúng ăn nhạt với những món dễ tiêu hóa như canh, rau hay cháo loãng kéo dài từ 1-2 tuần.</span></li>
            <li style="list-style-type: disc; font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Chế độ ăn cần phải được thay đổi nhẹ nhàng và từ từ để hệ tiêu hóa của chúng được thích nghi và cải thiện. Trường hợp bệnh trở nặng hơn, chúng ta nên đưa chúng đến cơ sở y tế gần nhất để kịp thời chữa trị.</span></li>
            <li style="list-style-type: disc; font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Đối với trường hợp bị xuất huyết đường ruột, chó cần được mang đến cơ sở thú ý gần nhất để được kê thuốc và chữa trị.</span></li>
            <li style="list-style-type: disc; font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Tuy nhiên, nếu bất đắc dĩ không thể đưa chúng đi khám, bạn nên cho chúng ăn cháo loãng và uống Oresol, vitamin C để bù lại nước và giúp chúng phục hồi nhanh hơn.</span></li>
            <li style="list-style-type: disc; font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Sau đó, chúng ta nên mua nước muối loãng và ống hút rửa ruột để rửa ruột cho cún cưng của chúng ta.</span></li>
            <li style="list-style-type: disc; font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 13pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Sau 4-5 điều trị, ta có thể cho chúng ăn kiều mạch với sữa hay cháo thịt băm để bổ sung dưỡng chất tuy nhiên nhất định phải cho chó di chuyển nhẹ nhàng, hạn đi lại nhiều.</span></li>
        </ul>
    </div>
    </div>
    
</asp:Content>
